### ISSUE TITLE
Add support for lambda

### ISSUE THREAD

**Issue by eholk** [google/schism#4]
Schism needs support for first class procedures.

**Comment by eholk** [comment]
I've started working on this on a branch at https://github.com/eholk/schism/tree/lambda

**Comment by eholk** [comment]
I'll use this comment to track the status of my lambda branch at https://github.com/eholk/schism/tree/lambda

## Tasks

* [x] Enable lambda expressions and closure values ([test case](https://github.com/eholk/schism/blob/lambda/test/lambda-1.ss))
* [ ] Capture free variables in lambdas
* [ ] Allow calling of closures
* [ ] Automatically wrap top-level functions in closures when in value position

**Comment by eholk** [comment]
As of https://github.com/eholk/schism/commit/95e2ed82f5d8c995440916a9b79888000577cb80, my lambda branch supports calling closures.

Capturing free variables shouldn't be far behind, and then we can get this merged into master.

Automatically wrapping functions is going to be tricky without changes to the calling convention. This is probably better done after we support varargs.
